// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDt1a1Zavhz6-DeChrOL1kuDd_vAXNl25Q',
    appId: '1:474193191799:web:679ff91fb3a0dd93f0f772',
    messagingSenderId: '474193191799',
    projectId: 'football-club-79164',
    authDomain: 'football-club-79164.firebaseapp.com',
    storageBucket: 'football-club-79164.appspot.com',
    measurementId: 'G-SLB09RL7NS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAig9mg7YNjEICYx9fHbMDluk-nffLYCjE',
    appId: '1:474193191799:android:1e1e0c082c306442f0f772',
    messagingSenderId: '474193191799',
    projectId: 'football-club-79164',
    storageBucket: 'football-club-79164.appspot.com',
  );
}
